#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Kanon Steam Arabic-B proxy string table.

This variant keeps the original Kanon offsets from ../patches.py, but writes
Arabic strings as Luck Engine-friendly visual text:

1. logical Arabic is shaped to Arabic Presentation Forms
2. each line is reversed for the engine's left-to-right text renderer

Strings that do not fit the original exe slot budget are intentionally kept in
English. The CSV generated by this script is the review file for what is
patched and what remains unchanged.
"""

from pathlib import Path
import importlib.util

HERE = Path(__file__).resolve().parent
BASE_PATH = HERE.parent / "patches.py"

spec = importlib.util.spec_from_file_location("kanon_base_patches", BASE_PATH)
base = importlib.util.module_from_spec(spec)
spec.loader.exec_module(base)


# tuple order: isolated, final, initial, medial
ARABIC_FORMS = {
    "ء": ("ﺀ", None, None, None),
    "آ": ("ﺁ", "ﺂ", None, None),
    "أ": ("ﺃ", "ﺄ", None, None),
    "ؤ": ("ﺅ", "ﺆ", None, None),
    "إ": ("ﺇ", "ﺈ", None, None),
    "ئ": ("ﺉ", "ﺊ", "ﺋ", "ﺌ"),
    "ا": ("ﺍ", "ﺎ", None, None),
    "ب": ("ﺏ", "ﺐ", "ﺑ", "ﺒ"),
    "ة": ("ﺓ", "ﺔ", None, None),
    "ت": ("ﺕ", "ﺖ", "ﺗ", "ﺘ"),
    "ث": ("ﺙ", "ﺚ", "ﺛ", "ﺜ"),
    "ج": ("ﺝ", "ﺞ", "ﺟ", "ﺠ"),
    "ح": ("ﺡ", "ﺢ", "ﺣ", "ﺤ"),
    "خ": ("ﺥ", "ﺦ", "ﺧ", "ﺨ"),
    "د": ("ﺩ", "ﺪ", None, None),
    "ذ": ("ﺫ", "ﺬ", None, None),
    "ر": ("ﺭ", "ﺮ", None, None),
    "ز": ("ﺯ", "ﺰ", None, None),
    "س": ("ﺱ", "ﺲ", "ﺳ", "ﺴ"),
    "ش": ("ﺵ", "ﺶ", "ﺷ", "ﺸ"),
    "ص": ("ﺹ", "ﺺ", "ﺻ", "ﺼ"),
    "ض": ("ﺽ", "ﺾ", "ﺿ", "ﻀ"),
    "ط": ("ﻁ", "ﻂ", "ﻃ", "ﻄ"),
    "ظ": ("ﻅ", "ﻆ", "ﻇ", "ﻈ"),
    "ع": ("ﻉ", "ﻊ", "ﻋ", "ﻌ"),
    "غ": ("ﻍ", "ﻎ", "ﻏ", "ﻐ"),
    "ف": ("ﻑ", "ﻒ", "ﻓ", "ﻔ"),
    "ق": ("ﻕ", "ﻖ", "ﻗ", "ﻘ"),
    "ك": ("ﻙ", "ﻚ", "ﻛ", "ﻜ"),
    "ل": ("ﻝ", "ﻞ", "ﻟ", "ﻠ"),
    "م": ("ﻡ", "ﻢ", "ﻣ", "ﻤ"),
    "ن": ("ﻥ", "ﻦ", "ﻧ", "ﻨ"),
    "ه": ("ﻩ", "ﻪ", "ﻫ", "ﻬ"),
    "و": ("ﻭ", "ﻮ", None, None),
    "ى": ("ﻯ", "ﻰ", None, None),
    "ي": ("ﻱ", "ﻲ", "ﻳ", "ﻴ"),
}


def _joins_next(ch):
    forms = ARABIC_FORMS.get(ch)
    return bool(forms and forms[2])


def _joins_prev(ch):
    forms = ARABIC_FORMS.get(ch)
    return bool(forms and forms[1])


def _shape_arabic(text):
    out = []
    chars = list(text)
    for i, ch in enumerate(chars):
        forms = ARABIC_FORMS.get(ch)
        if not forms:
            out.append(ch)
            continue

        prev_ch = chars[i - 1] if i > 0 else ""
        next_ch = chars[i + 1] if i + 1 < len(chars) else ""
        join_prev = _joins_prev(ch) and _joins_next(prev_ch)
        join_next = _joins_next(ch) and _joins_prev(next_ch)

        isolated, final, initial, medial = forms
        if join_prev and join_next and medial:
            out.append(medial)
        elif join_prev and final:
            out.append(final)
        elif join_next and initial:
            out.append(initial)
        else:
            out.append(isolated)
    return "".join(out)


def A(text):
    """Arabic-B: shaped Arabic Presentation Forms, reversed per line."""
    return "\n".join("".join(reversed(_shape_arabic(line))) for line in text.split("\n"))


# Short Arabic labels only. Each final visual string must fit the original
# hardcoded slot budget; patches.py validates this and aborts on overflow.
ARABIC_TARGETS = {
    # Bottom / Basic
    0x4874A4: "إغ",
    0x488B98: "ضبط",
    0x499104: "ع",
    0x4991A0: "قائمة",
    0x499144: "إخف",
    0x499208: "تخ",
    0x4991B0: "مقروء",
    0x499248: "مكان",
    0x499230: "أس",
    0x499238: "وس",
    0x499320: "صت",
    0x4992D0: "قف",
    0x4992E8: "لا توقف",
    0x499398: "تاريخ",
    0x499450: "المؤشر",
    0x4993A8: "نعم",
    0x499420: "لا",
    0x499490: "اهتزاز",
    0x499470: "لا",

    # Text / colors
    0x49A4D0: "نص",
    0x49A4D8: "لغة",
    0x49A598: "خط",
    0x49A5D4: "صلب",
    0x49A5FC: "شف",
    0x49A618: "شفافية",
    0x49A630: "خيار",
    0x49A658: "مقروء",
    0x49A688: "لون",
    0x49A6D0: "خض",
    0x49A6D8: "زر",
    0x49A6F0: "بن",
    0x49A494: "بر",
    0x49A4C0: "صف",
    0x49A700: "لون",
    0x49AABC: "نص",
    0x49AB30: "سرعة",
    0x49AAEC: "بط",
    0x49AAF4: "سر",
    0x49ABB0: "انتظار",
    0x49AC08: "مهلة",

    # Sound / voice / keyboard
    0x49AC5C: "صوت",
    0x49AC68: "عام",
    0x49AD08: "نظام",
    0x49AD30: "صغير",
    0x49ADF0: "ضغط",
    0x49AE00: "بدء",
    0x49AEC0: "لا",
    0x49AED0: "حفظ",
    0x49AF20: "تحميل",
    0x49AF80: "لغة",
    0x49AFE0: "فوق",

    # Mouse / system
    0x49B02C: "ماو",
    0x49B080: "نظام",
    0x49B090: "اخفاء",
    0x49B0E8: "يمين",
    0x49B108: "يسار يم",
    0x49B120: "عجلة",
    0x49B180: "رجوع",
    0x49B190: "فوق",
    0x49B1F0: "تقدم",
    0x49B200: "تحت",
    0x49B280: "صفحات",
    0x49B298: "موافقة",
    0x49B2F4: "فعل",
    0x49B310: "لمس",
    0x49B350: "حوار",
    0x49B3D8: "مؤشر",
    0x49B748: "نسخة",
    0x49B76C: "نظم",
    0x49B7B0: "نف",
    0x49B7B8: "ملء",
    0x49B7E0: "وضع",
    0x49B820: "آل",
    0x49B870: "حجم",

    # Prompts / save menu / toggles
    0x487EB0: "تحميل؟",
    0x4880C8: "استبدال؟",
    0x488080: "حفظ؟",
    0x4882F0: "حذف الحفظ؟",
    0x488350: "لا يحذف",
    0x488B2C: "حذف",
    0x488B54: "آخر",
    0x488EE8: "عرض",
    0x489008: "تطبق إعدادات النص",
    0x487458: "ع",
    0x4987E8: "لا",
    0x499358: "ن",
    0x4883F8: "للرئيسية؟",
    0x4883A0: "قائمة؟",
    0x487478: "ن",
    0x48748C: "ﻻ",
    0x4882B8: "حفظ",
    0x495C58: "تريد الخروج؟",
}


def _decode_source(src_bytes):
    return src_bytes.decode("utf-8", errors="replace")


def _resolved_patches():
    resolved = []
    for off, src, target, context, note in base.PATCHES:
        if off in ARABIC_TARGETS:
            target = A(ARABIC_TARGETS[off])
            note = f"{note}; Arabic-B logical='{ARABIC_TARGETS[off]}'"
        elif not target:
            target = _decode_source(src)
            note = f"{note}; unchanged in Arabic-B"
        resolved.append((off, src, target, context, note))
    return resolved


def main():
    base.GAME_EXE = r"C:\Program Files (x86)\Steam\steamapps\common\Kanon\Kanon.exe"
    base.PATCH_GAME_NAME = "Kanon Arabic-B"
    base.PATCH_VERSION = "0.1-ar-b"
    base.PATCHES = _resolved_patches()
    base.main()


if __name__ == "__main__":
    main()
