// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialogueDetectFormat(arg1) {
  return window['go']['main']['App']['DialogueDetectFormat'](arg1);
}

export function DialogueExtractBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DialogueExtractBatch'](arg1, arg2, arg3);
}

export function DialogueExtractFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DialogueExtractFile'](arg1, arg2, arg3);
}

export function DialogueImportBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DialogueImportBatch'](arg1, arg2, arg3, arg4);
}

export function DialogueImportFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DialogueImportFile'](arg1, arg2, arg3, arg4);
}

export function FontEdit(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['FontEdit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function FontExtract(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FontExtract'](arg1, arg2, arg3, arg4);
}

export function GetLuckSystemPath() {
  return window['go']['main']['App']['GetLuckSystemPath']();
}

export function ImageBatchExport(arg1, arg2) {
  return window['go']['main']['App']['ImageBatchExport'](arg1, arg2);
}

export function ImageBatchImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImageBatchImport'](arg1, arg2, arg3, arg4);
}

export function ImageExport(arg1, arg2) {
  return window['go']['main']['App']['ImageExport'](arg1, arg2);
}

export function ImageImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImageImport'](arg1, arg2, arg3, arg4);
}

export function PakExtract(arg1, arg2) {
  return window['go']['main']['App']['PakExtract'](arg1, arg2);
}

export function PakFontExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['PakFontExtract'](arg1, arg2, arg3);
}

export function PakFontReplace(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PakFontReplace'](arg1, arg2, arg3, arg4, arg5);
}

export function PakReplace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PakReplace'](arg1, arg2, arg3, arg4);
}

export function ScanGameData() {
  return window['go']['main']['App']['ScanGameData']();
}

export function ScriptCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ScriptCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ScriptDecompile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ScriptDecompile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectOutputDir(arg1) {
  return window['go']['main']['App']['SelectOutputDir'](arg1);
}

export function SelectPakFile() {
  return window['go']['main']['App']['SelectPakFile']();
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}

export function SelectSaveScriptFile(arg1) {
  return window['go']['main']['App']['SelectSaveScriptFile'](arg1);
}

export function SelectSaveTsvFile(arg1) {
  return window['go']['main']['App']['SelectSaveTsvFile'](arg1);
}

export function SelectScriptTxtFile() {
  return window['go']['main']['App']['SelectScriptTxtFile']();
}

export function SelectTsvFile() {
  return window['go']['main']['App']['SelectTsvFile']();
}

export function SetLuckSystemPath() {
  return window['go']['main']['App']['SetLuckSystemPath']();
}

export function StopProcess() {
  return window['go']['main']['App']['StopProcess']();
}
